before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - replacements:
      darwin: macOS
      linux: Linux
      386: 32-bit
      amd64: 64-bit
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
brews:
  - name: despell
    tap:
      owner: bensadeh
      name: homebrew-despell
    description: "despell puts icons in tmux's statusline"
    homepage: "https://github.com/bensadeh/despell/"
    license: "MIT"
