[default]
nerdfont = "icon1"
color = "none"
emoji = "emoji1"

[icons.command1]
nerdfont = "icon2"
color = "blue"
emoji = "emoji2"

[icons.command2]
nerdfont = "icon3"
color = "magenta"
emoji = "emoji3"