name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build and Test
        run: |
          cargo build --verbose
          cargo test --verbose

      - name: Check Cargo.lock
        run: |
          git diff --exit-code -- Cargo.lock
          if [ $? -ne 0 ]; then
            echo "Cargo.lock was modified. Please commit the changes."
            exit 1
          fi

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo login $CARGO_REGISTRY_TOKEN
          cargo publish

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "none"  # No artifacts
          token: ${{ secrets.GH_PAT }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: "Release for ${{ github.ref }}"
